---
name: dartsort
channels:
    - conda-forge
dependencies:
    - python=3.14
    - h5py
    - ipykernel
    - ipython
    - ipywidgets
    - kdepy
    - linear_operator
    - matplotlib
    - numba
    - numpy>=2.0
    - opt-einsum
    - pandas
    - pip
    - pydantic
    - pytest
    - pytorch>=2.0
    - scipy>=1.13
    - scikit-learn
    - tqdm
